DEVICE_NAME='dc-'

TRAFFMONETIZER_TOKEN='FzQ5006VWiKJKhgWYKmqxbiCOz14N1WsMM1/DDtK7K0='
UR_AUTH_TOKEN=''
UR_NETWORK_PROXY_MODE=true
EARN_FM_API='69910370-eece-437f-8a7d-4489426bdffb'
USE_EARN_FM_FLEETSHARE=true

USE_DNS_OVER_HTTPS=true
USE_PROXIES=true
USE_MULTI_IP=true
ENABLE_LOGS=false
DELAY_BETWEEN_CONTAINER=1
AUTO_UPDATE_CONTAINERS=true
#MAX_MEMORY=1254m
#MEMORY_RESERVATION=
#MEMORY_SWAP=512m
#CPU=1

########################## User Configuration Ends here ##########################
