DEVICE_NAME=

WIPTER_EMAIL='sjsqaq2333001@outlook.com'
WIPTER_PASSWORD='KamijuTouma2333,./'

IPROYALS_EMAIL='sjsqaq2333@163.com'
IPROYALS_PASSWORD='KamijuTouma2333'

TRAFFMONETIZER_TOKEN='FzQ5006VWiKJKhgWYKmqxbiCOz14N1WsMM1/DDtK7K0='

UR_AUTH_TOKEN=''

CASTAR_SDK_KEY='cskL1swBy8xDUp'

USE_MULTI_IP=true
USE_PROXIES=true
AUTO_UPDATE_CONTAINERS=true

ENABLE_LOGS=false

#MAX_MEMORY=102m
#MEMORY_RESERVATION=
#CPU=1
DELAY_BETWEEN_CONTAINER=5


########################## User Configuration Ends here ##########################
